resilience4j:
  circuitbreaker:
    instances:
      StudentAPI-service:
        failure-rate-threshold: 50
        ring-buffer-size-in-closed-state: 3
        ring-buffer-size-in-half-open-state: 2
        wait-duration-in-open-state: 20s
        automatic-transition-from-open-to-half-open-enabled: true 